SIMILARS_SKU_COMPARATOR/SIMILARS_SKU_COMPARATOR/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'SIMILARS_SKU_COMPARATOR.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^comparator/', include('comparator.urls',namespace="comparator")),
    url(r'^admin/', include(admin.site.urls)),
]

SIMILARS_SKU_COMPARATOR/comparator/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^details$', views.details, name='details'),
    url(r'^(?P<sku_id>\w+)/results$', views.results, name='results'),
]

SIMILARS_SKU_COMPARATOR/comparator/models.py
from django.db import models
#select max(char_length(lien_image)) from CATALOG 
class Sku(models.Model):
        sku_id = models.CharField(max_length=200)
        sku_one_picture_url = models.CharField(max_length=200,default='')
        sku_one_picture_url = models.CharField(max_length=200,default='')
        sku_two_picture_url = models.CharField(max_length=200,default='')
        sku_two_picture_url = models.CharField(max_length=200,default='')
        sku_one_picture_url = models.CharField(max_length=200,default='')
        sku_one_picture_url = models.CharField(max_length=200,default='')
        sku_three_picture_url = models.CharField(max_length=200,default='')
        sku_three_picture_url = models.CharField(max_length=200,default='')
        sku_four_picture_url = models.CharField(max_length=200,default='')
        sku_four_picture_url = models.CharField(max_length=200,default='')
        sku_five_picture_url = models.CharField(max_length=200,default='')
        sku_five_picture_url = models.CharField(max_length=200,default='')
        sku_six_picture_url = models.CharField(max_length=200,default='')
        sku_six_picture_url = models.CharField(max_length=200,default='')
        def __str__(self):              # __unicode__ on Python 2
                return self.sku_id

SIMILARS_SKU_COMPARATOR/comparator/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render
from comparator.datacollector import Datacollector

# Create your views here
def details(request):
    sku_id=request.POST['sku_id']
    return HttpResponseRedirect(reverse('comparator:results', args=(sku_id,)))

def results(request,sku_id):  
    my_cds_pictures,my_kriter_pictures = Datacollector.get_pictures(sku_id)
    context = {'sku_id': sku_id, 'my_cds_pictures':my_cds_pictures, 'my_kriter_pictures':my_kriter_pictures}
    return render(request, 'comparator/results.html', context)

def index(request):
    context = {}
    return render(request, 'comparator/index.html', context)

SIMILARS_SKU_COMPARATOR/comparator/templates/comparator/index.html
<h1> Enter the SKU for which you want to compare results : </h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

 
<form action="{% url 'comparator:details'%}" method="post">
{% csrf_token %}
SKU identification : <br>
<input type="text" name="sku_id">
<br>
<input type="submit" value="Compare" />
</form>

SIMILARS_SKU_COMPARATOR/comparator/templates/comparator/results.html
<h1>Cdiscount similar products<h1>
  {% if my_cds_pictures %}
    <ul>
    {% for picture in my_cds_pictures %}
        <li><img src={{picture}} alt="pouet"></li>
    {% endfor %}
    </ul>
{% endif %}
<h1>Kriter similar products<h1>
{% if my_kriter_pictures %}
    <ul>
    {% for picture in my_kriter_pictures %}
        <li><img src={{picture}} alt="pouet"></li>
    {% endfor %}
    </ul>
{% endif %}